/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CreateShipmentRouteImport } from './routes/create-shipment'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ShipmentShipmentIdRouteImport } from './routes/shipment/$shipmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateShipmentRoute = CreateShipmentRouteImport.update({
  id: '/create-shipment',
  path: '/create-shipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentShipmentIdRoute = ShipmentShipmentIdRouteImport.update({
  id: '/shipment/$shipmentId',
  path: '/shipment/$shipmentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-shipment': typeof CreateShipmentRoute
  '/dashboard': typeof DashboardRoute
  '/shipment/$shipmentId': typeof ShipmentShipmentIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-shipment': typeof CreateShipmentRoute
  '/dashboard': typeof DashboardRoute
  '/shipment/$shipmentId': typeof ShipmentShipmentIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-shipment': typeof CreateShipmentRoute
  '/dashboard': typeof DashboardRoute
  '/shipment/$shipmentId': typeof ShipmentShipmentIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/create-shipment' | '/dashboard' | '/shipment/$shipmentId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/create-shipment' | '/dashboard' | '/shipment/$shipmentId'
  id:
    | '__root__'
    | '/'
    | '/create-shipment'
    | '/dashboard'
    | '/shipment/$shipmentId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateShipmentRoute: typeof CreateShipmentRoute
  DashboardRoute: typeof DashboardRoute
  ShipmentShipmentIdRoute: typeof ShipmentShipmentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-shipment': {
      id: '/create-shipment'
      path: '/create-shipment'
      fullPath: '/create-shipment'
      preLoaderRoute: typeof CreateShipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipment/$shipmentId': {
      id: '/shipment/$shipmentId'
      path: '/shipment/$shipmentId'
      fullPath: '/shipment/$shipmentId'
      preLoaderRoute: typeof ShipmentShipmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateShipmentRoute: CreateShipmentRoute,
  DashboardRoute: DashboardRoute,
  ShipmentShipmentIdRoute: ShipmentShipmentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
